version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sentinel_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_DB: sentinel
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      TZ: America/La_Paz
    networks:
      - general_network
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis:7
    container_name: sentinel_redis
    networks:
      - general_network
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  postgres_data:
  redis_data:

networks:
  general_network:
    external: true

secrets:
  postgres_password:
    external: true
