version: '3.8'

services:
  api:
    image: sentinel-api:latest
    deploy:
      labels:
        - "traefik.enable=true"

        # 📌 Router para el API
        - "traefik.http.routers.sentinelapi.rule=Host(`api.sentinel.kurukin.com`)"
        - "traefik.http.routers.sentinelapi.entrypoints=websecure"
        - "traefik.http.routers.sentinelapi.tls=true"
        - "traefik.http.routers.sentinelapi.tls.certresolver=le"

        # 📌 Puerto interno de la app
        - "traefik.http.services.sentinelapi.loadbalancer.server.port=3000"
    networks:
      - general_network
      - traefik_public
    secrets:
      - postgres_password
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_DB: sentinel
      POSTGRES_HOST: sentinel-data_postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

networks:
  general_network:
    external: true
  traefik_public:
    external: true

secrets:
  postgres_password:
    external: true
